Mayhem Fuzzing
mayhemheroes/openmls pull request #1
Opened 2022-04-26 23:36 UTC by shreyasphx

Added fuzzing integration with Mayhem

2022-05-05 06:20 UTC, xansec requested changes

2022-05-05 06:20 UTC, xansec commented on Mayhemfile
> +cmds:
Please either use only a single command, or separate this Mayhemfile into multiple Mayhemfiles as discussed here: https://community.forallsecure.com/t/error-the-mayhem-for-code-scan-detected-the-mayhem-run-for-your-target-was-unsuccessful-and-multiple-docker-files-in-the-repository/350/5

2022-05-05 06:20 UTC, xansec commented on Mayhemfile
> +target: openml
Please make sure that the target name matches the target binary. So, if you were fuzzing `welcome_decode`, your target name should be `welcome_decode`

2022-05-09 23:15 UTC, shreyasphx commented
Reduced to 1 fuzz target in the mayhem file

2022-05-09 23:48 UTC, xansec commented
LGTM!

2022-05-09 23:48 UTC, merged